mod 'stdlib',
  :git => 'git://github.com/puppetlabs/puppetlabs-stdlib.git',
  :ref => '4.1.0'
  
mod 'composer',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/composer'

mod 'php5',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/php5'

mod 'uglify',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/uglify'

mod 'foreman',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/foreman'

mod 'mysql',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/mysql'

mod 'redis',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/redis'

mod 'memcached',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/memcached'

mod 'socket-redis',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/socket-redis'

mod 'nginx',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/nginx'

mod 'bipbip',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/bipbip'
